POST http://localhost:3001/api/v1/payments
Content-Type: application/json

{
    "product_id": "prod_001",
    "quantity": 2,
    "payment_method": "card",
    "amount": 100
}

###

GET http://localhost:3001/api/v1/payments


###

PUT http://localhost:3001/api/v1/payments/:paymentId/status
Content-Type: application/json

{
    "status": "paid"
}

###


GET http://localhost:3001/api/v1/payments/:paymentId

###

DELETE http://localhost:3001/api/v1/payments/:paymentId